In [10]:
%matplotlib inline
%load_ext autoreload
%autoreload 2
%reload_ext autoreload
import pyximport; 
pyximport.install()

import sys
import os
sys.path.insert(1,'../cylib')

import numpy as np

from tSVD import *


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [11]:
a = np.arange(1,31, dtype=np.float64).reshape(5,6)

(array([[ 0.09159048, -0.76918679],
        [ 0.24235368, -0.49124914],
        [ 0.39311689, -0.21331289],
        [ 0.54388011,  0.06462598],
        [ 0.69464332,  0.3425597 ]]),
 array([97.13375854,  4.47569466]),
 array([[ 0.35619327,  0.37642911,  0.39666498,  0.41690081,  0.43713668,
          0.45737255],
        [ 0.62803388,  0.38973272,  0.1514318 , -0.08686972, -0.32517099,
         -0.56347179]]))